; PlatformIO - UART LED Control & Switch Monitor
[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino
upload_protocol = stlink
monitor_speed = 115200
debug_tool = stlink

upload_flags =
    -c
    set CPUTAPID 0x2ba01477