; PlatformIO - LED Control & Switch Monitor
; Hardware: STM32F103 (Blue Pill) + ESP32 sebagai USB-UART bridge
; STM32 PA9(TX)→ESP32 GPIO16(RX2),  PA10(RX)←ESP32 GPIO17(TX2)
[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino
upload_protocol = stlink
monitor_speed = 115200